apiVersion: v1
kind: Secret
metadata:
  name: mssql
type: Opaque
data:
  SA_PASSWORD: UGFzc3dvcmQxMjM=
  DB_CONN_URL: c3Fsc2VydmVyOi8vc2E6UGFzc3dvcmQxMjNAbG9jYWxob3N0OjE0MzM/ZGF0YWJhc2U9bWFzdGVyJmNvbm5lY3Rpb24rdGltZW91dD0zMCZlbmNyeXB0PWRpc2FibGUmdHJ1c3RzZXJ2ZXJjZXJ0aWZpY2F0ZT10cnVl