apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql-service
spec:
  selector:
    app: mssql-deployment
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: gateway-server
spec:
  selector:
    app: gateway-deployment
  ports:
    - protocol: TCP
      name: http
      port: 9900
      targetPort: 9900
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP