# CI for running tests on GitHub Actions

name: Go CI
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: go build -v ./server/cmd/...
        name: Build

      - run: go test -v ./tests/...
        working-directory: ./server
        name: Run tests

      - run: go test -coverprofile=coverage.out ./tests/... && go tool cover -func=coverage.out && go tool cover -html=coverage.out -o coverage.html
        name: Upload coverage to Codecov
        working-directory: ./server
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
